/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Utils.Formatacao;
import DAO.VendaDAO;
import Entidade.Venda;
import TableModel.VendaTableModel;
import Utils.JTableUtilities;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;

/**
 *
 * @author Gui
 */
public class DlgBuscaVenda extends javax.swing.JDialog {

    IfrVenda ifrVendaLocal = null;
    JDesktopPane dskPrincipal = new JDesktopPane();
    VendaTableModel tableModel = new VendaTableModel();
    /**
     * Creates new form DlgPesquisarVenda
     */
    public DlgBuscaVenda(java.awt.Frame parent, boolean modal, IfrVenda ifrVenda) {
        super(parent, modal);
        initComponents();
        Formatacao.formatarData(tffDataInicio);
        Formatacao.formatarData(tffDataFinal);
        ifrVendaLocal = ifrVenda;
        tblBuscaVenda.setModel(tableModel);
        tblBuscaVenda.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblBuscaVenda.getColumnModel().getColumn(1).setPreferredWidth(780);
        JTableUtilities.setCellsAlignment(tblBuscaVenda, SwingConstants.CENTER, new int[]{0, 1});
        tblBuscaVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//seleção de única linha
    }

    private DlgBuscaVenda(JFrame jFrame, boolean b) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        tblBuscaVenda.setModel(tableModel);
        tblBuscaVenda.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblBuscaVenda.getColumnModel().getColumn(1).setPreferredWidth(780);
        JTableUtilities.setCellsAlignment(tblBuscaVenda, SwingConstants.CENTER, new int[]{0, 1});
        tblBuscaVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//seleção de única linha
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDataInicio = new javax.swing.JLabel();
        tffDataInicio = new javax.swing.JFormattedTextField();
        lblDataFim = new javax.swing.JLabel();
        tffDataFinal = new javax.swing.JFormattedTextField();
        lblCliente = new javax.swing.JLabel();
        tfdNomeCliente = new javax.swing.JTextField();
        btnPesquisarPessoa = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscaVenda = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Venda");

        lblDataInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataInicio.setText("Data Inicial");

        lblDataFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataFim.setText("Data Final");

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCliente.setText("Cliente");

        btnPesquisarPessoa.setText("Pesquisar");
        btnPesquisarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPessoaActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        tblBuscaVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBuscaVenda);

        btnExcluir.setText("Editar Situação");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataInicio)
                                .addGap(18, 18, 18)
                                .addComponent(tffDataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataFim)
                                .addGap(24, 24, 24)
                                .addComponent(tffDataFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                        .addGap(533, 533, 533))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblCliente)
                        .addGap(43, 43, 43)
                        .addComponent(tfdNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarPessoa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicio)
                    .addComponent(tffDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataFim)
                    .addComponent(tffDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(tfdNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarPessoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSelecionar)
                    .addComponent(btnExcluir))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPessoaActionPerformed
        String nome = tfdNomeCliente.getText();
        String dataini = tffDataInicio.getText();
        String datafim = tffDataFinal.getText();
        String status = "a";
        new VendaDAO().popularTabela(tblBuscaVenda, nome, dataini, datafim);
        tffDataInicio.setValue(null);
        tffDataFinal.setValue(null);
        tfdNomeCliente.setText("");
        tffDataInicio.requestFocus();
    }//GEN-LAST:event_btnPesquisarPessoaActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
            String cod = String.valueOf(tblBuscaVenda.getValueAt(tblBuscaVenda.getSelectedRow(), 0));
            String nome = String.valueOf(tblBuscaVenda.getValueAt(tblBuscaVenda.getSelectedRow(), 1));
            String clientecod = String.valueOf(tblBuscaVenda.getValueAt(tblBuscaVenda.getSelectedRow(), 2));
            String datavenda = String.valueOf(tblBuscaVenda.getValueAt(tblBuscaVenda.getSelectedRow(), 3));
            String pessoanome = String.valueOf(tblBuscaVenda.getValueAt(tblBuscaVenda.getSelectedRow(), 4));
            String pessoacod = String.valueOf(tblBuscaVenda.getValueAt(tblBuscaVenda.getSelectedRow(), 5));
            

            ifrVendaLocal.definirVenda(cod, nome, clientecod, datavenda, pessoanome, pessoacod);
            

            this.dispose();
   
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja inativar esta venda?");

        System.out.println("Opção = " + opcao);

        if (opcao == JOptionPane.OK_OPTION) {

            String codString = String.valueOf(tblBuscaVenda.getValueAt(tblBuscaVenda.getSelectedRow(), 0));

            int cod = Integer.parseInt(codString);
            
            Venda venda = new VendaDAO().findById(Integer.parseInt(codString));

            String retorno = new VendaDAO().salvar(venda);
            
            int aux = Integer.parseInt(retorno);
            
            System.out.println("Esse é o retorno = "+retorno);
            
            System.out.println("Esse é o ID = "+cod);


            if (aux == cod) {
                JOptionPane.showMessageDialog(null, "Registro excluído/inativado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Ops, problemas ao excluir/inativar registro.");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgBuscaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgBuscaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgBuscaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgBuscaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgBuscaVenda dialog = new DlgBuscaVenda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisarPessoa;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDataFim;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JTable tblBuscaVenda;
    private javax.swing.JTextField tfdNomeCliente;
    private javax.swing.JFormattedTextField tffDataFinal;
    private javax.swing.JFormattedTextField tffDataInicio;
    // End of variables declaration//GEN-END:variables
}
